<a href="https://colab.research.google.com/github/Dimitri250/Formative-Assignment-PCA-Dimitri-Kwihangana/blob/main/Formative_Assignment_PCA_Dimitri_Kwihangana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [ ]:
#import necessary package
#TO DO
import numpy as np


In [ ]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

In [ ]:
mean = np.mean(data,axis=0)
std_dev = np.std(data, axis=0)
standardized_data = (data - mean) / std_dev
print (standardized_data)


[[-1.36438208  0.70710678  1.5109662  -0.99186978  0.77802924]
 [ 0.12403473 -1.94454365 -0.13736056  0.77145428 -2.06841919]
 [-0.62017367  0.1767767   0.68680282 -0.99186978  0.20873955]
 [ 1.61245155  0.1767767  -1.78568733  0.33062326  0.20873955]
 [-0.62017367  1.23743687 -0.13736056 -0.77145428  1.00574511]
 [ 0.86824314 -0.35355339 -0.13736056  1.65311631 -0.13283426]]


Handling data on the same scale is crucial because it ensures that all features contribute equally to the analysis. Without standardization, features with larger scales would dominate the results, leading to biased and inaccurate conclusions. This equalizes the influence of each feature, allowing algorithms like PCA to accurately identify the true patterns and relationships in the data, rather than being misled by the magnitude of the feature values

![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [ ]:
cov_matrix = np.cov(standardized_data, rowvar=False)

print(cov_matrix)

[[ 1.2        -0.42098785 -1.0835838   0.90219291 -0.37000528]
 [-0.42098785  1.2         0.20397003 -0.77149364  1.18751836]
 [-1.0835838   0.20397003  1.2        -0.59947269  0.22208218]
 [ 0.90219291 -0.77149364 -0.59947269  1.2        -0.70017993]
 [-0.37000528  1.18751836  0.22208218 -0.70017993  1.2       ]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [ ]:

eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



Eigenvalues:
 [4.74189469e-05 4.94531029e-02 4.04085720e-01 1.73655615e+00
 3.80985761e+00]
Eigenvectors:
 [[ 0.28128049  0.70733581 -0.03317471 -0.45182808 -0.4640131 ]
 [ 0.6706731  -0.29051532 -0.15803498 -0.48800851  0.45019005]
 [ 0.24186072  0.48462321 -0.5029143   0.55665017  0.37929082]
 [-0.03373724 -0.36999674 -0.78311558 -0.03162214 -0.4976889 ]
 [-0.64143906  0.20861365 -0.32822489 -0.49682965  0.43642295]]


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [ ]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list
# Sort eigenvalues and eigenvectors
order_of_importance = np.argsort(eigenvalues)[::-1]
print('The order of importance is :\n {}'.format(order_of_importance))

sorted_eigenvalues = eigenvalues[order_of_importance]
print('\n\n Sorted eigenvalues:\n{}'.format(sorted_eigenvalues))

sorted_eigenvectors = eigenvectors[:, order_of_importance]  # Sort the columns
print('\n\n The sorted eigenvector matrix is: \n {}'.format(sorted_eigenvectors))


The order of importance is :
 [4 3 2 1 0]


 Sorted eigenvalues:
[3.80985761e+00 1.73655615e+00 4.04085720e-01 4.94531029e-02
 4.74189469e-05]


 The sorted eigenvector matrix is: 
 [[-0.4640131  -0.45182808 -0.03317471  0.70733581  0.28128049]
 [ 0.45019005 -0.48800851 -0.15803498 -0.29051532  0.6706731 ]
 [ 0.37929082  0.55665017 -0.5029143   0.48462321  0.24186072]
 [-0.4976889  -0.03162214 -0.78311558 -0.36999674 -0.03373724]
 [ 0.43642295 -0.49682965 -0.32822489  0.20861365 -0.64143906]]


Question:

1. Why do we order eigen values and eigen vectors?

    Answer: Ordering eigenvalues and eigenvectors allows us to identify and prioritize the principal components that contribute the most variance to the dataset, aiding in effective dimensionality reduction and data interpretation

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

    Answer:No, it's not true that we would consider the lowest eigenvalue compared to the highest. In fact, we prioritize the eigenvectors corresponding to the highest eigenvalues because they capture the most variance in the data. This is because higher eigenvalues signify higher variance along those principal components, making them more important for retaining the essential information in the dataset during dimensionality reduction


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [ ]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = (sorted_eigenvalues / np.sum(sorted_eigenvalues)) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print(explained_variance)

['63.50%', '28.94%', '6.73%', '0.82%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [ ]:
k = 2 # select the number of principal components

reduced_data = sorted_eigenvectors[:, order_of_importance[:k]]
reduced_data = np.matmul(standardized_data, reduced_data)

In [ ]:
print(reduced_data)

[[-0.00968857  0.09104374]
 [-0.00174858 -0.13085023]
 [ 0.0097965   0.25334771]
 [-0.00482511  0.14501926]
 [ 0.00315329 -0.36948581]
 [ 0.00331248  0.01092534]]


In [ ]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations

**Positive Effects**

**1.Dimensionality Reduction:** PCA reduces the number of features while retaining most of the dataset's variance, simplifying models and improving computational efficiency.

**2.Noise Reduction**: By focusing on principal components with the highest variance, PCA can filter out noise and improve the signal-to-noise ratio in the data.

**Negative Effects of PCA**

**1.Loss of Interpretability:** The transformed principal components are linear combinations of the original features, making it difficult to interpret their meanings.

**2.Information Loss:** If too many principal components are discarded, significant information might be lost, potentially affecting the model's performance.





